# Generated by Django 6.0.3 on 2026-04-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_post_like',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
