# Generated by Django 6.0.3 on 2026-04-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_recruiterprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
